# Prod

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - environments/prod/security/**
      - modules/security/**
      - pipelines/prod/terraform-prod-security.yml
      - pipelines/templates/**

pr:
  autoCancel: true
  branches:
    include:
      - main
  paths:
    include:
      - environments/prod/security/**
      - modules/security/**
      - pipelines/prod/terraform-prod-security.yml
      - pipelines/templates/**

pool:
  name: MultiOsPool
  demands:
    - Agent.Name -equals prod-win-vm-age

stages:
  - template: ../templates/terraform-domain.yml
    parameters:
      environmentName: prod
      domainName: security
      terraformWorkingDirectory: environments/prod/security
      serviceConnection: sc-ealz-prod
      backendResourceGroup: rg-ealz-tfstate-eus2-001
      backendStorageAccount: stealztfstate001
      backendContainer: tfstate
      backendKey: prod-security.tfstate
      deploymentEnvironment: prod