trigger:
  branches:
    include:
      - main
  paths:
    include:
      - environments/dev/security/**
      - modules/security/**
      - pipelines/dev/terraform-dev-security.yml
      - pipelines/templates/**

pr:
  autoCancel: true
  branches:
    include:
      - main
  paths:
    include:
      - environments/dev/security/**
      - modules/security/**
      - pipelines/dev/terraform-dev-security.yml
      - pipelines/templates/**

pool:
  name: MultiOsPool
  demands:
    - Agent.Name -equals prod-win-vm-age

stages:
  - template: ../templates/terraform-domain.yml
    parameters:
      environmentName: dev
      domainName: security
      terraformWorkingDirectory: environments/dev/security
      serviceConnection: sc-ealz-dev
      backendResourceGroup: rg-ealz-tfstate-eus2-001
      backendStorageAccount: stealztfstate001
      backendContainer: tfstate
      backendKey: dev-security.tfstate
      deploymentEnvironment: dev